### ISSUE TITLE
./gradlew webpack fails

### ISSUE THREAD

**Issue by amgohan** [Widen/spring-react-demo#1]
./gradlew webpack
:npmInstall
npm WARN package.json spring-react-demo@1.0.0 No description
npm WARN package.json spring-react-demo@1.0.0 No repository field.
npm WARN package.json spring-react-demo@1.0.0 No README data
:webpack

> spring-react-demo@1.0.0 webpack /home/sbouhamidi/git/spring-react-demo/src/main/webapp
> node node_modules/webpack/bin/webpack -w

Hash: 83b92d31b62611db8213
Version: webpack 1.12.9
Time: 328ms
    + 1 hidden modules

ERROR in ./name-manager.jsx
Module build failed: SyntaxError: /home/sbouhamidi/git/spring-react-demo/src/main/webapp/name-manager.jsx: Unexpected token (12:12)
  10 |     render() {
  11 |         return (
> 12 |             <div>
     |             ^
  13 |                 <NameAdder url="/name" onAdded={this.handleNameAdded.bind(this)}/>
  14 |                 <NamesList url="/names" ref="namesList"/>
  15 |             </div>
    at Parser.pp.raise (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseExprAtom (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:510:12)
    at Parser.pp.parseExprSubscripts (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseParenAndDistinguishExpression (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:583:26)
    at Parser.pp.parseExprAtom (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:469:19)
    at Parser.pp.parseExprSubscripts (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExpression (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:85:19)
    at Parser.pp.parseReturnStatement (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:313:26)
    at Parser.pp.parseStatement (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:101:19)
    at Parser.pp.parseBlockBody (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:527:25)
    at Parser.pp.parseBlock (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:482:8)
    at Parser.pp.parseFunctionBody (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:886:22)
    at Parser.pp.parseMethod (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:855:8)
    at Parser.pp.parseClassMethod (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:795:8)
    at Parser.pp.parseClassBody (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:756:10)
    at Parser.pp.parseClass (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:639:8)
    at Parser.pp.parseStatement (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:96:19)
    at Parser.pp.parseBlockBody (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:527:25)
    at Parser.pp.parseTopLevel (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:29:8)
    at Parser.parse (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:96:17)
    at Object.parse (/home/sbouhamidi/git/spring-react-demo/src/main/webapp/node_modules/babel-core/node_modules/babylon/lib/index.js:44:50)
> Building 50% > :webpack

**Comment by rnicholus** [comment]
Probably caused by breaking changes in babel 2.x. This repo isn't really maintained anymore, but if you'd like to use it, you will either need to specify explicit 1.x versions for webpack/babel in the [package.json](https://github.com/Widen/spring-react-demo/blob/master/src/main/webapp/package.json) file, or make appropriate adjustments to the webpack/babel config such that this is usable with the latest versions of each library.

**Comment by rnicholus** [comment]
A more up-to-date and maintained example of the frontend stuff can be found at https://github.com/Widen/fullstack-react.
